name: git diff
author: Rodrigo Martinez Diaz
description: Returns a JSON object stringify with the list of files created, modified and deleted
inputs:
  source-branch:
    description: The pull request branch
    required: true
  target-branch:
    description: The name of the branch you want to merge the PR
    required: true
outputs:
  diff-summary:
    description: A JSON stringify with three properties modified, created, deleted each one  containing a list of filepaths

runs:
  using: 'node16'
  main: 'dist/index.js'
