name: generate site
author: Rodrigo Martinez Diaz
description: Generate an static site for visualize and analyze the PR changes with the target branch
inputs:
  commit-hash:
    description: The commit hash of the head of the PR changes
    required: true
  wait:
    description: Milliseconds to simulate the time spent building the website
    required: true
  base-directory:
    description: It should be the workspace directory used when running the actions
    required: true 
runs:
  using: 'node16'
  main: 'dist/index.js'
