name: Covera report
author: Rodrigo Martinez Diaz
description: Retrieve the code coverage results to compute other metrics
inputs:
  use-coverage-report:
    description: Indicates if it should use the previously computed coverage report
    required: false
    default: 'false'
  coverage-artifact-path:
    description: Path to the coverage summary report JSON file
    required: false
    default: ''
  coverage-artifact-name:
    description: The name used to store the coverage as an artifact
    required: false
    default: ''
  
runs:
  using: 'node16'
  main: 'dist/index.js'
