name: Notify Website Deployment
author: Rodrigo Martinez Diaz
description: Add a comment to the PR with a link to the website URL
inputs:
  website-url:
    description: The netlify url on which the website has been deployed
    required: true
  GITHUB_TOKEN:
    description: A github token
    required: true
  
runs:
  using: 'node16'
  main: './index.js'
