name: Build & commit
on: [push]
jobs:
  build-commit:
    name: "Build & commit actions"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build scripts
        run: yarn workspaces foreach -pt run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: 'chore: compiling actions'
          commit_author: Author <actions@github.com>

